// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Channel struct {
	Channelname string `json:"channelname"`
	Created     string `json:"created"`
	Password    string `json:"password"`
}

type Video struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Uploader    string `json:"uploader"`
	Uploaded    string `json:"uploaded"`
	Processed   int64  `json:"processed"`
}
