allowed_origins = ["http://localhost:*", "https://localhost:*", "http://127.0.0.1:*", "https://127.0.0.1:*"]
base_url = "http://localhost:8001"
db_time_format = "2006-01-02 15:04:05"
paseto_duration = "720h"
paseto_key = "Vmtab2QxSnJNSGRQVlZaWFZsaE9URU5u"
port = "8001"
resolution = [768, 432]
secret_key = "VmtkMFUxUnJNVlpOVnpWcFpXcENURU5u"
